app: poulpe

image:
  #name: Voluntarily left commented. The real value will be passed at deployment time
  pullPolicy: IfNotPresent # You can put Always in case of a moving tag (eg: latest)

service:
  name: poulpe
  type: NodePort
  port: 8080

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 1
    memory: 100Mi

replicas: 5

prometheus:
  active: true
